var = [{'category': 'General Knowledge', 'type': 'boolean', 'difficulty': 'medium',
        'question': 'The average woman is 5 inches / 13 centimeters shorter than the average man.',
        'correct_answer': 'True', 'incorrect_answers': ['False']},
       {'category': 'General Knowledge', 'type': 'boolean', 'difficulty': 'easy',
        'question': 'On average, at least 1 person is killed by a drunk driver in the United States every hour.',
        'correct_answer': 'True', 'incorrect_answers': ['False']},
       {'category': 'Mythology', 'type': 'boolean', 'difficulty': 'medium',
        'question': 'The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.',
        'correct_answer': 'False', 'incorrect_answers': ['True']},
       {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'easy',
        'question': 'The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.',
        'correct_answer': 'False', 'incorrect_answers': ['True']},
       {'category': 'Entertainment: Television', 'type': 'boolean', 'difficulty': 'medium',
        'question': 'In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.',
        'correct_answer': 'True', 'incorrect_answers': ['False']},
       {'category': 'Entertainment: Film', 'type': 'boolean', 'difficulty': 'easy',
        'question': '&quot;Minions&quot; was released on the June 10th, 2015.', 'correct_answer': 'False',
        'incorrect_answers': ['True']},
       {'category': 'Entertainment: Video Games', 'type': 'boolean', 'difficulty': 'easy',
        'question': 'In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.',
        'correct_answer': 'False', 'incorrect_answers': ['True']},
       {'category': 'Entertainment: Music', 'type': 'boolean', 'difficulty': 'medium',
        'question': 'Nick Mason is the only member to appear on every Pink Floyd album.', 'correct_answer': 'True',
        'incorrect_answers': ['False']},
       {'category': 'General Knowledge', 'type': 'boolean', 'difficulty': 'easy',
        'question': 'Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.',
        'correct_answer': 'False', 'incorrect_answers': ['True']},
       {'category': 'General Knowledge', 'type': 'boolean', 'difficulty': 'medium',
        'question': 'The British organisation CAMRA stands for The Campaign for Real Ale.', 'correct_answer': 'True',
        'incorrect_answers': ['False']}]
